edu/urls.py
from . import views
from django.conf.urls import url, include, handler404
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='register/login.html'), name='login'),
    url(r'^register/$', auth_views.LoginView.as_view(template_name='register/login.html'), name='register'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='register/logout.html'), name='logout'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^password_reset/$',
        auth_views.PasswordResetView.as_view(template_name='register/password_reset_form.html'),
        name='password_reset'),
    url(r'^password_reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='register/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='register/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/done/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='register/password_reset_complete.html'),
        name='password_reset_complete'),
    url(r'^$', views.index, name="dashboard"),

]
# student_course
urlpatterns += [
    url(r'^student_course/list/(?P<pk>[0-9]+)$', views.StudentCourseListView.as_view(), name='StudentCourseListView'),
    url(r'^student_course/update/(?P<pk_tcc>[0-9]+)$', views.StudentCourseUpdateView.as_view(),
        name='StudentCourseUpdateView'),
]
# Teacher Presence
urlpatterns += [
    url(r'^teacher_presence/create/(?P<pk>[0-9]+)$', views.TeacherPresenceCreateView.as_view(),
        name='TeacherPresenceCreateView'),
    # url(r'^teacher_presence/view/$', views.StudentCreateView.as_view(), name='TeacherPresenceListView'),

]
# student
urlpatterns += [
    url(r'^student/create/$', views.StudentCreateView.as_view(), name='StudentCreateView'),
    url(r'^student/list/$', views.StudentListView.as_view(), name='StudentListView'),
    url(r'^student/detail/(?P<pk>[0-9]+)/$', views.StudentDetailView.as_view(), name='StudentDetail'),
    url(r'^student/edit/(?P<pk>[0-9]+)/$', views.StudentUpdateView.as_view(), name='StudentEdit'),
]
# User url
urlpatterns += [
    url(r'^user/list/$', views.UserListView.as_view(), name='UserListView'),
    url(r'^user/edit/(?P<pk>[0-9]+)/$', views.UserEditView.as_view(), name='UserEditView'),
    url(r'^user/detail/(?P<pk>[0-9]+)/$', views.UserDetailView.as_view(), name='UserDetailView'),
    url(r'^user/create/$', views.UserCreateView.as_view(), name='UserCreateView'),
]
# Teacher urls
urlpatterns += [
    url(r'^teacher/create/$', views.TeacherCreateView.as_view(), name='TeacherCreateView'),
    url(r'^teacher/list/$', views.TeacherListView.as_view(), name='TeacherListView'),
    url(r'^teacher/detail/(?P<pk>[0-9]+)/$', views.TeacherDetailView.as_view(), name='TeacherDetail'),
    url(r'^teacher/edit/(?P<pk>[0-9]+)/$', views.TeacherUpdateView.as_view(), name='TeacherEdit'),
]
# TeacherCourseClass urls
urlpatterns += [
    url(r'^class/List/$', views.TeacherClassCourseListView.as_view(), name='TeacherClassCourseList'),
    url(r'^class/details/(?P<pk>[0-9]+)/$', views.TeacherClassCourseDetailView.as_view(),
        name='TeacherClassCourseDetails'),
    url(r'^class/create/$', views.TeacherClassCourseCreateView.as_view(), name='TeacherClassCourseCreate'),
    url(r'^class/edit/(?P<pk>[0-9]+)/$', views.TeacherClassCourseUpdateView.as_view(), name='TeacherClassCourseEdit'),
]

# Course
urlpatterns += [
    url(r'^course/List/$', views.CourseList.as_view(), name='CourseList'),
    url(r'^course/details/(?P<pk>[0-9]+)/$', views.CourseDetail.as_view(), name='CourseDetail'),
    url(r'^course/create/$', views.CourseCreate.as_view(), name='CourseCreate'),
    url(r'^course/edit/(?P<pk>[0-9]+)/$', views.CourseUpdate.as_view(), name='CourseUpdate'),
]
# Classrooms
urlpatterns += [
    url(r'^classroom/List/$', views.ClassroomList.as_view(), name='ClassroomList'),
    url(r'^classroom/student/details/(?P<pk>[0-9]+)/$', views.ClassroomStudentDetail.as_view(),
        name='ClassroomStudentDetail'),
    url(r'^classroom/course/details/(?P<pk>[0-9]+)/$', views.ClassroomCourseDetail.as_view(),
        name='ClassroomCourseDetail'),
    url(r'^classroom/create/$', views.ClassroomCreate.as_view(), name='ClassroomCreate'),
    url(r'^classroom/edit/(?P<pk>[0-9]+)/$', views.ClassroomUpdate.as_view(), name='ClassroomUpdate'),
]

# Register
urlpatterns += [
    url(r'^register/List/$', views.RegisterList.as_view(), name='RegisterList'),
    url(r'^register/details/(?P<pk>[0-9]+)/$', views.RegisterDetail.as_view(), name='RegisterDetail'),
    url(r'^register/create/$', views.RegisterCreate.as_view(), name='RegisterCreate'),
    url(r'^register/edit/(?P<pk>[0-9]+)/$', views.RegisterUpdate.as_view(), name='RegisterUpdate'),
]
# class time
urlpatterns += [
    url(r'^first_setup/$', views.first_setup, name='first_setup'),
]
# student presence
urlpatterns += [
    url(r'^dashboard/activity/$', views.TeacherClassCourseListView.as_view(), name='activity'),
    url(r'^dashboard/activity/grade/(?P<pk_tcc>[0-9]+)/students$', views.StudentCourseListView.as_view(),
        name='students_grade'),
    url(r'^dashboard/activity/presence/(?P<pk_tcc>[0-9]+)/create$', views.StudentPresenceCreateView.as_view(),
        name='student_presence_create'),
    url(r'^dashboard/activity/presence/(?P<pk_tcc>[0-9]+)$', views.StudentPresenceListView.as_view(),
        name='student_presence_list'),
]

simorgh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers




# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
from . import  settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('edu.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

edu/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import jdatetime


# Create your models here.

# abstract person
class Person(models.Model):
    birthday = models.DateField(verbose_name='تاریخ تولد', blank=True, null=True)
    last_modified_date = models.DateTimeField(verbose_name='تاریخ آخرین ویرایش', auto_now_add=True, blank=True,
                                              null=True)
    photo = models.ImageField(upload_to='profiles', null=True, blank=True, verbose_name='تصویر پروفایل')
    father_name = models.CharField(max_length=40, verbose_name='نام پدر', blank=True, null=True)

    class Meta:
        abstract = True


class Student(Person, models.Model):
    student_id = models.IntegerField(verbose_name='شماره دانش آموزی')
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='نام کاربری', primary_key=True,
                                related_name='student')
    courses = models.ManyToManyField("Course", through='StudentCourse', related_name='students',
                                     verbose_name='دورس ')
    classrooms = models.ManyToManyField("Classroom", through='Register', related_name='students',
                                        verbose_name='کلاس ها')
    math, humanities, experimental = 'MA', 'HU', 'EX'
    CHOICE_education_field = (
        (math, 'ریاضی و فیزیک'),
        (humanities, 'علوم انسانی'),
        (experimental, 'علوم تجربی')
    )

    education_field = models.CharField(max_length=2, choices=CHOICE_education_field, verbose_name='رشته تحصیلی',
                                       blank=True, null=True)

    class Meta:
        verbose_name = 'دانش آموز'
        verbose_name_plural = 'دانش آموزان'

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

    @property
    def first_name(self):
        return self.user.first_name

    @property
    def last_name(self):
        return self.user.last_name


class Teacher(Person, models.Model):
    teacher_id = models.IntegerField(verbose_name='کد پرسنلی')
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='نام کاربری', primary_key=True,
                                related_name='teacher')
    hire_date = models.DateField(verbose_name='تاریخ استخدام')
    DIPLOMA, ASSOCIATE, BACHELOR, MASTER, PHD = 'DI', 'FD', 'LI', 'FL', 'DR'
    CHOICE_DEGREE = (
        (ASSOCIATE, 'کاردانی'),
        (BACHELOR, 'کارشناسی'),
        (MASTER, 'کارشناسی ارشد'),
        (PHD, 'دکتری'),
        (DIPLOMA, 'دیپلم'),
    )
    edu_degree = models.CharField(max_length=2, choices=CHOICE_DEGREE, verbose_name='مدرک تحصیلی')
    profession = models.ManyToManyField('Course', verbose_name='تخصص', blank=True)

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

    class Meta:
        verbose_name = 'آموزگار'
        verbose_name_plural = 'آموزگاران'

    @property
    def experience(self):
        return datetime.now().year - self.hire_date.year


class LevelField(models.Model):
    FIRST, SECOND, THIRD = '10', '11', '12',
    CHOICE_LEVEL = (
        (FIRST, 'پایه دهم'),
        (SECOND, 'پایه یازدهم'),
        (THIRD, 'پایه دوازدهم'),
    )
    level = models.CharField(max_length=2, choices=CHOICE_LEVEL, verbose_name='پایه تحصیلی')
    HUMANITY, MATH, NATURAL = 'HU', 'MA', 'NA'
    CHOICE_FIELD = (
        (HUMANITY, 'علوم انسانی'),
        (MATH, 'علوم ریاضی'),
        (NATURAL, 'علوم تجربی'),
    )
    field = models.CharField(max_length=2, choices=CHOICE_FIELD, verbose_name='رشته تحصیلی')

    class Meta:
        verbose_name = 'لیست پایه های تحصیلی'
        verbose_name_plural = 'لیست پایه های تحصیلی'

    def __str__(self):
        return self.get_level_display() + " " + self.get_field_display()


class Classroom(models.Model):
    A, B = 'A', 'B'
    CHOICE_GROUP = (
        (A, 'کلاس الف'),
        (B, 'کلاس ب'),
    )
    branch = models.CharField(max_length=1, choices=CHOICE_GROUP, verbose_name='شماره کلاس')
    level_field = models.ForeignKey("LevelField", on_delete=models.SET_NULL, null=True, verbose_name='مقطع تحصیلی')
    education_year = models.CharField(max_length=20, null=True, verbose_name='سال تحصیلی')
    courses = models.ManyToManyField('Course', through='TeacherClassCourse', related_name='classrooms',
                                     verbose_name='دروس')
    teachers = models.ManyToManyField('Teacher', through='TeacherClassCourse', related_name='classrooms',
                                      verbose_name='اساتید')

    class Meta:
        verbose_name = 'کلاس'
        verbose_name_plural = 'کلاس ها'

    def __str__(self):
        return str(self.level_field) + " " + self.get_branch_display()


class Course(models.Model):
    name = models.CharField(max_length=100, verbose_name='نام درس')
    unit = models.IntegerField(null=True, verbose_name='تعداد واحد')
    level_field = models.ForeignKey('LevelField', on_delete=models.SET_NULL, null=True, verbose_name='مقطع تحصیلی')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'درس'
        verbose_name_plural = 'دروس'


class StudentCourse(models.Model):
    student = models.ForeignKey('Student', related_name='student_courses', on_delete=models.SET_NULL, null=True,
                                blank=True)
    course = models.ForeignKey('Course', related_name='student_courses', on_delete=models.SET_NULL, null=True,
                               blank=True)
    final_grade = models.FloatField(null=True, blank=True)
    mid_grade = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.student.__str__() + self.course.__str__()


class Register(models.Model):
    classroom = models.ForeignKey('Classroom', related_name='registers', on_delete=models.SET_NULL, null=True)
    student = models.ForeignKey('Student', related_name='registers', on_delete=models.SET_NULL, null=True)
    is_active = models.BooleanField(verbose_name='فعال', help_text='برای غیرفعال کردن کلاس از این گزینه استفاده کنید',
                                    default=True)


class TeacherClassCourse(models.Model):
    teacher = models.ForeignKey('Teacher', related_name='teacher_class_course', on_delete=models.SET_NULL, null=True,
                                verbose_name='نام استاد')
    course = models.ForeignKey('Course', related_name='teacher_class_course', on_delete=models.SET_NULL, null=True,
                               verbose_name='نام درس')
    classroom = models.ForeignKey('Classroom', related_name='teacher_class_course', on_delete=models.SET_NULL,
                                  null=True, verbose_name='پایه تحصیلی')
    class_times = models.ManyToManyField('ClassTime', related_name='teacher_class_course', verbose_name='زمان کلاس')
    is_active = models.BooleanField(verbose_name='فعال', help_text='برای غیرفعال کردن کلاس از این گزینه استفاده کنید',
                                    default=True)


class ClassTime(models.Model):
    MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY = 'MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU'
    CHOICE_DAY = (
        (SATURDAY, 'شنبه'),
        (SUNDAY, 'یکشنبه'),
        (MONDAY, 'دوشنبه'),
        (TUESDAY, 'سه شنبه'),
        (WEDNESDAY, 'چهارشنبه'),
        (THURSDAY, 'پنجشنبه'),
        (FRIDAY, 'جمعه'),
    )
    class_day = models.CharField(max_length=2, choices=CHOICE_DAY, verbose_name='روز کلاس', blank=True, null=True)
    FIRST, SECOND, THIRD, FORTH = 'FI', 'SE', 'TH', 'FO'
    CHOICE_TIME = (
        (FIRST, 'زنگ اول'),
        (SECOND, 'زنگ دوم'),
        (THIRD, 'زنگ سوم'),
        (FORTH, 'زنگ چهارم'),
    )
    class_time = models.CharField(max_length=2, choices=CHOICE_TIME, verbose_name='زنگ', blank=True, null=True)

    def __str__(self):
        return self.get_class_day_display() + ' ' + self.get_class_time_display()

    @property
    def time(self):
        return self.get_class_time_display()

    @property
    def day(self):
        return self.get_class_day_display()


class StudentPresence(models.Model):
    student_course = models.ForeignKey('StudentCourse', on_delete=models.CASCADE)
    presence = models.BooleanField(verbose_name='حضور')
    date = models.DateField('تاریخ', )
    class_time = models.ForeignKey('ClassTime', on_delete=models.SET_NULL, null=True)


class TeacherPresence(models.Model):
   teacher_class_course = models.ForeignKey('TeacherClassCourse',on_delete=models.CASCADE)
   presence = models.BooleanField(verbose_name='حضور')
   date = models.DateField('تاریخ', )
   class_time = models.ForeignKey('ClassTime',on_delete=models.CASCADE)

edu/templates/edu/change_password.html
{% extends 'formbase.html' %}
{% load static from staticfiles %}
{% block title %}
     {{ user.get_full_name }} به سامانه سیمرغ خوش آمدید
{% endblock %}
{% block dashboard-title %}
    تغییر کلمه عبور
    {% endblock %}

{% block form_title %}
    تغییر کلمه عبور
{% endblock %}
{% block form_body %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

    {% load widget_tweaks %}

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% for field in form.visible_fields %}
    <div class="form-group col-6 float-right">
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}
<div class="form-group col-12 float-right">
  <button type="submit" class="btn btn-primary">تایید </button>
    </div>
</form>

{% endblock %}

edu/templates/edu/class_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Class List</title>
</head>
<body>
<h1>
    {{classroom.get_field_display}} {{classroom.get_level_display}} {{classroom.get_group_display}}
</h1>
<table>
    <tr>
        <th>{{teacher.user.first_name}}
            {{teacher.user.last_name}}
        </th>
        <th>نام دبیر</th>
    </tr>
    {% for i in student_list %}
    <tr>
        <td>{{i.user.last_name}}</td>
        <td>{{i.user.first_name}}</td>
    </tr>
    {% endfor %}
</table>
</body>
</html>

edu/templates/edu/classroomcourse_detail.html
{% extends 'tablesbase.html' %}
{% load static from staticfiles %}
{% block title %}
    {{ user.get_full_name }} به سامانه سیمرغ خوش آمدید
{% endblock %}
{% block dashboard-title %}
    لیست درس ها
{% endblock %}

{% block tabel_title %}جدول اطلاعات درس ها{% endblock %}
{% block tabel_new_item_link %}{% url 'CourseCreate' %}{% endblock %}
{% block tabel_new_item %} ایجاد درس جدید{% endblock %}
{% block tabel_header %}
    <th style="text-align: center;width:25px;">ردیف</th>
    <th style="text-align: center">نام درس</th>
    <th style="text-align: center">پایه تحصیلی</th>
    <th style="text-align: center;width: 100px;">تعداد واحد</th>
    <th style="text-align: center;width: 120px;">ویرایش</th>
{% endblock %}
{% block tabel_footer %}
    <th style="width:25px;">ردیف</th>
    <th>نام درس</th>
    <th>پایه تحصیلی</th>
    <th>تعداد واحد</th>
    <th>ویرایش</th>
{% endblock %}
{% block tabel_body %}
    {% for course in classroom.courses.all %}
        <tr>
            <th>{{ forloop.counter }}</th>
            <td>{{ course.name }}</td>
            <td>{{ course.level_field }}</td>
            <td >{{ course.unit }}</td>
            <td style="text-align: center;">
                <a href="{% url 'CourseUpdate' course.pk %}"><i class="far fa-edit"></i></a>
                <a href="{% url 'CourseDetail' course.pk %}"><i class="fas fa-info-circle"></i></a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

edu/templates/edu/course_form.html
{% extends 'formbase.html' %}
{% load static from staticfiles %}
{% block title %}
     {{ user.get_full_name }} به سامانه سیمرغ خوش آمدید
{% endblock %}
{% block dashboard-title %}
     فرم ثبت درس جدید
    {% endblock %}

{% block form_title %}
    فرم ثبت درس
{% endblock %}
{% block form_body %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

    {% load widget_tweaks %}

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% for field in form.visible_fields %}
    <div class="form-group col-6 float-right">
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}
<div class="col-12 float-right mb-2">
  <button type="submit" class="btn btn-primary">تایید و ثبت اطلاعات</button>
    </div>
</form>

{% endblock %}

edu/templates/edu/course_list.html
{% extends 'tablesbase.html' %}
{% load static from staticfiles %}
{% block title %}
    {{ user.get_full_name }} به سامانه سیمرغ خوش آمدید
{% endblock %}
{% block dashboard-title %}
    لیست درس ها
{% endblock %}

{% block tabel_title %}جدول اطلاعات درس ها{% endblock %}
{% block tabel_new_item_link %}{% url 'CourseCreate' %}{% endblock %}
{% block tabel_new_item %} ایجاد درس جدید{% endblock %}
{% block tabel_header %}
    <th style="text-align: center;width:25px;">ردیف</th>
    <th style="text-align: center">نام درس</th>
    <th style="text-align: center">پایه تحصیلی</th>
    <th style="text-align: center;width: 100px;">تعداد واحد</th>
    <th style="text-align: center;width: 120px;">ویرایش</th>
{% endblock %}
{% block tabel_footer %}
    <th style="width:25px;">ردیف</th>
    <th>نام درس</th>
    <th>پایه تحصیلی</th>
    <th>تعداد واحد</th>
    <th>ویرایش</th>
{% endblock %}
{% block tabel_body %}
    {% for course in course_list %}
        <tr>
            <th>{{ forloop.counter }}</th>
            <td>{{ course.name }}</td>
            <td>{{ course.level_field }}</td>
            <td >{{ course.unit }}</td>
            <td style="text-align: center;">
                <a href="{% url 'CourseUpdate' course.pk %}"><i class="far fa-edit"></i></a>
                <a href="{% url 'CourseDetail' course.pk %}"><i class="fas fa-info-circle"></i></a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

edu/templates/edu/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block title %}
     {{ user.get_full_name }} به سامانه سیمرغ خوش آمدید
{% endblock %}

{% block content %}
    {{ message }}
{% endblock %}

edu/templates/edu/register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <title>Student register form</title>
</head>
<body>
<div class="container" style="margin-top: 20px;">
    {% load widget_tweaks %}

<form method="post" novalidate>
  {% csrf_token %}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
</body>
</html>

edu/templates/edu/register_list.html
{% extends 'tablesbase.html' %}
{% load static from staticfiles %}
{% block title %}
    {{ user.get_full_name }} به سامانه سیمرغ خوش آمدید
{% endblock %}
{% block dashboard-title %}
    لیست دانش آموزهای ثبت نام شده
{% endblock %}

{% block tabel_title %}جدول دانش آموزان ثبت نام شده{% endblock %}
{% block tabel_new_item_link %}{% url 'RegisterCreate' %}{% endblock %}
{% block tabel_new_item %} ثبت نام{% endblock %}
{% block tabel_header %}
    <th style="width:10px;">ردیف</th>
    <th>پایه تحصیلی</th>
    <th>کلاس</th>
    <th>سال تحصیلی</th>
    <th>لیست درس-استاد</th>
    <th> دانش آموزان</th>
{% endblock %}
{% block tabel_footer %}
    <th style="width:10px;">ردیف</th>
    <th>پایه تحصیلی</th>
    <th>کلاس</th>
    <th>سال تحصیلی</th>
    <th style="width: 140px">لیست درس-استاد</th>
    <th style="width: 120px"> دانش آموزان</th>
{% endblock %}
{% block tabel_body %}
    {% for register in register_list %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ register.classroom.level_field }}</td>
            <td>{{ register.classroom.get_branch_display }}</td>
            <td>{{ register.classroom.education_year }}</td>
            <td align="center"><a href="{% url 'ClassroomCourseDetail' register.classroom.pk %}"><i class="fas fa-chalkboard-teacher"></i></a></td>
            <td align="center"><a href="{% url 'ClassroomStudentDetail' register.classroom.pk %}"><i class="fas fa-user-graduate"></i></a></td>
        </tr>
    {% endfor %}
{% endblock %}

edu/templates/edu/student_list.html
{% extends 'tablesbase.html' %}
{% load static from staticfiles %}
{% block title %}
    {{ user.get_full_name }} به سامانه سیمرغ خوش آمدید
{% endblock %}
{% block dashboard-title %}
    لیست دانش آموزان
{% endblock %}

{% block tabel_title %}جدول اطلاعات دانش آموزان {% endblock %}
{% block tabel_new_item_link %}{% url 'StudentCreateView' %}{% endblock %}
{% block tabel_new_item %} ثبت دانش آموز جدید{% endblock %}
{% block tabel_header %}
    <th style="max-width:35px;">ردیف</th>
    <th width="130px">شماره دانش آموزی</th>
    <th>نام</th>
    <th>نام خانوادگی</th>
    <th> نام پدر</th>
    <th> تاریخ تولد</th>
    <th>رشته تحصیلی</th>
    <th> ابزار</th>
{% endblock %}
{% block tabel_footer %}
    <th style="width:25px;">ردیف</th>
    <th>شماره دانش آموزی</th>
    <th>نام</th>
    <th>نام خانوادگی</th>
    <th> نام پدر</th>
    <th> تاریخ تولد</th>
    <th>رشته تحصیلی</th>
    <th> ابزار</th>
{% endblock %}
{% block tabel_body %}
    {% for student in student_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ student.student_id }}</td>
            <td>{{ student.user.first_name }}</td>
            <td>{{ student.user.last_name }}</td>
            <td>{{ student.father_name }}</td>
            <td>{{ student.birthday }}</td>
            <td>{{ student.get_education_field_display }}</td>

            <td align="center"><a href="{% url 'StudentDetail' student.pk %}"><i
                    class="fas fa-info-circle ml-1"></i></a><a
                    href="{% url 'StudentEdit' student.pk %}"><i class="far fa-edit"></i></a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}
{% block filter_form %}
    <form class="form">
        {% csrf_token %}

        {{ search.non_field_errors }}
        <div class="form-group">
            {{ search.subject.errors }}
            <label for="{{ search.first_name.id_for_label }}">نام: </label>
            {{ search.first_name }}
        </div>
        <div class="form-group">
            {{ search.message.errors }}
            <label for="{{ search.last_name.id_for_label }}">نام خانوادگی: </label>
            {{ search.last_name }}
        </div>
        <div class="form-group">
            {{ search.sender.errors }}
            <label for="{{ search.user_name.id_for_label }}">نام کاربری :</label>
            {{ search.user_name }}
        </div>
        <div>
            <button type="submit" class="btn btn-primary">جست و جو</button>
        </div>
    </form>
{% endblock %}